package:
  name: py_snap_helpers
  version: "0.0.3"

source:
  path: ../py_snap_helpers

#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyinstrument = pyinstrument:main
    #
    # Would create an entry point called pyinstrument that calls pyinstrument.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    #test_cioppy.py

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://project.terradue.com/
  license: EUPL License
  summary: "Helpers for SNAP and Python"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

